/**
 * The starter pattern library.
 *
 * Picture blocks are drawn on an 8x8 grid of 1.5" cells - fine enough to read
 * as a cow, coarse enough that the piece count stays sane. The two traditional
 * star blocks use coarser grids because that is how they are actually built.
 */

export const FABRICS = {
  sky: { name: 'Sky blue solid', hex: '#CFE3F2' },
  grass: { name: 'Meadow green', hex: '#9DBB7A' },
  black: { name: 'Charcoal solid', hex: '#2B2622' },
  white: { name: 'Cream muslin', hex: '#F4F1EA' },
  snow: { name: 'Snow white', hex: '#F7F7F5' },
  madder: { name: 'Madder red', hex: '#B8453A' },
  indigo: { name: 'Indigo', hex: '#2F4A7A' },
  sage: { name: 'Sage', hex: '#7E9A7A' },
  pine: { name: 'Deep pine', hex: '#3F5F4A' },
  bark: { name: 'Walnut brown', hex: '#6E4A32' },
  oat: { name: 'Oatmeal linen', hex: '#E7DDCB' },
  butter: { name: 'Butter yellow', hex: '#EBD27A' },
  water: { name: 'Lake blue', hex: '#5C86B5' },
  rose: { name: 'Dusty rose', hex: '#D9A3A0' },
};

const F = FABRICS;

export const LIBRARY = [
  {
    id: 'cow',
    name: 'Cow, side profile',
    subject: 'Farm',
    blurb: 'The block that started it all. A flat, crayon-simple cow in four fabrics.',
    fabrics: { k: F.sky, g: F.grass, b: F.black, w: F.white },
    accent: 'b',
    rotate: ['#2B2622', '#6E4A32', '#B8453A', '#2F4A7A'],
    rows: [
      'k k k k k k k k',
      'k k k k k k k k',
      'k k k/b b b b w w',
      'k k b b b b w w',
      'k k b b b b w w',
      'k k b b b b k k',
      'g g b g g b g g',
      'g g b g g b g g',
    ],
  },
  {
    id: 'mug',
    name: 'Coffee mug',
    subject: 'Kitchen',
    blurb: 'Twelve of these in twelve fabrics make the sampler quilt everyone asks for.',
    fabrics: { c: F.oat, m: F.madder },
    accent: 'm',
    rotate: ['#B8453A', '#2F4A7A', '#7E9A7A', '#EBD27A', '#D9A3A0', '#6E4A32'],
    rows: [
      'c c c c c c c c',
      'c c c c c c c c',
      'c m m m m m c c',
      'c m m m m m m m',
      'c m m m m m c m',
      'c m m m m m m m',
      'c m\\c m m m m/c c c',
      'c c c c c c c c',
    ],
  },
  {
    id: 'cat',
    name: 'Sitting cat',
    subject: 'Pets',
    blurb: 'Ears from two half-square triangles, tail from one more. Two fabrics.',
    fabrics: { e: F.oat, t: F.black },
    accent: 't',
    rotate: ['#2B2622', '#6E4A32', '#D9A3A0', '#7E9A7A'],
    rows: [
      'e e e e e e e e',
      'e e e/t e e e\\t e e',
      'e e t t t t e e',
      'e e t t t t e e',
      'e e/t t t t t e\\t e',
      'e t t t t t t e',
      'e t t t t t t e\\t',
      'e t t t t t t t',
    ],
  },
  {
    id: 'sailboat',
    name: 'Sailboat',
    subject: 'Outdoors',
    blurb: 'One big sail on the diagonal, a hull with clipped corners, a strip of lake.',
    fabrics: { k: F.sky, s: F.white, h: F.madder, w: F.water },
    accent: 's',
    rotate: ['#F4F1EA', '#EBD27A', '#D9A3A0', '#9DBB7A'],
    rows: [
      'k k k k k k k k',
      'k k k k k/s k k k',
      'k k k k/s s k k k',
      'k k k/s s s k k k',
      'k k/s s s s k k k',
      'k k k k k k k k',
      'k/h h h h h h h k\\h',
      'w w w w w w w w',
    ],
  },
  {
    id: 'barn',
    name: 'Red barn',
    subject: 'Farm',
    blurb: 'A gable roof stepped out of half-square triangles, doors in the middle.',
    fabrics: { k: F.sky, r: F.madder, d: F.black, g: F.grass },
    accent: 'r',
    rotate: ['#B8453A', '#2F4A7A', '#7E9A7A', '#6E4A32'],
    rows: [
      'k k k k k k k k',
      'k k k k/r k\\r k k k',
      'k k k/r r r k\\r k k',
      'k k/r r r r r k\\r k',
      'k r r r r r r k',
      'k r r d d r r k',
      'k r r d d r r k',
      'g g g g g g g g',
    ],
  },
  {
    id: 'mountain',
    name: 'Mountain with snow',
    subject: 'Outdoors',
    blurb: 'Snow cap, indigo slopes, a band of forest along the bottom.',
    fabrics: { k: F.sky, n: F.snow, m: F.indigo, f: F.pine },
    accent: 'm',
    rotate: ['#2F4A7A', '#5C86B5', '#6E4A32', '#7E9A7A'],
    rows: [
      'k k k k k k k k',
      'k k k k/n k\\n k k k',
      'k k k/n n n k\\n k k',
      'k k/m m m m m k\\m k',
      'k/m m m m m m m k\\m',
      'm m m m m m m m',
      'f f f f f f f f',
      'f f f f f f f f',
    ],
  },
  {
    id: 'pine',
    name: 'Pine tree',
    subject: 'Outdoors',
    blurb: 'Four tiers of triangles, a stubby trunk, snow on the ground.',
    fabrics: { k: F.sky, t: F.pine, r: F.bark, n: F.snow },
    accent: 't',
    rotate: ['#3F5F4A', '#7E9A7A', '#2F4A7A', '#9DBB7A'],
    rows: [
      'k k k k k k k k',
      'k k k k/t k\\t k k k',
      'k k k/t t t k\\t k k',
      'k k/t t t t t k\\t k',
      'k/t t t t t t t k\\t',
      'k k k r r k k k',
      'k k k r r k k k',
      'n n n n n n n n',
    ],
  },
  {
    id: 'cowskis',
    name: 'Cow with skis',
    subject: 'Custom',
    blurb: 'Someone asked for this and nobody had a pattern. Now there is one.',
    custom: true,
    fabrics: { k: F.sky, n: F.snow, b: F.black, w: F.white, s: F.madder },
    accent: 'b',
    rotate: ['#2B2622', '#6E4A32', '#B8453A'],
    rows: [
      'k k k k k k k k',
      'k k k k k k k k',
      'k k k/b b b b w w',
      'k k b b b b w w',
      'k k b b b b w w',
      'k k b b b b k k',
      'n n b n n b n n',
      'n s s s n s s s',
    ],
  },

  // --- traditional blocks, on the grids they are actually drafted on --------
  {
    id: 'sawtooth-star',
    name: 'Sawtooth star',
    subject: 'Traditional',
    blurb: 'Eight flying geese around a plain centre. The block every sampler starts with.',
    grid: 4,
    fabrics: { k: F.oat, s: F.indigo, c: F.madder },
    accent: 's',
    rotate: ['#2F4A7A', '#B8453A', '#7E9A7A', '#6E4A32'],
    rows: [
      'k   s^k .   k',
      's<k c   c   s>k',
      '.   c   c   .',
      'k   svk .   k',
    ],
  },
  {
    id: 'ohio-star',
    name: 'Ohio star',
    subject: 'Traditional',
    blurb: 'Four hourglass units and five squares. Nine pieces of geometry, no curves anywhere.',
    grid: 3,
    fabrics: { k: F.oat, c: F.madder },
    accent: 'c',
    rotate: ['#B8453A', '#2F4A7A', '#3F5F4A', '#EBD27A'],
    rows: [
      'k   c+k k',
      'k+c c   k+c',
      'k   c+k k',
    ],
  },
];

export const SUBJECTS = [...new Set(LIBRARY.map((b) => b.subject))];

export const PRICING = {
  block10: 10,
  block12: 15,
  full: 22,
  custom: 35,
};
